### ISSUE TITLE
Suggestion  - either give a a link or use span instead

### ISSUE THREAD

**Issue by jzhu01** [josewunder/prj-rev-bwfs-dasmoto#2]
Seen here: https://github.com/josewunder/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/Index.html#L14

Since the a tags are links, you need an href for them in the HTML. If you don't want to use a tags, you can use span tags instead. :)

**Comment by josewunder** [comment]
<p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span style="color:blue;font-weight:bold">Starting at $3.00 / brush </span>.</p>

Excellent tip, thanks J!
